# Generated by Django 2.2.7 on 2019-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_securities',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
