# Generated by Django 2.2.7 on 2019-11-23 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191123_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='volume',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_of_transaction',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='shares',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Asset'),
        ),
    ]
