# Generated by Django 2.2.7 on 2019-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191123_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_type',
            field=models.CharField(max_length=12),
        ),
    ]
