# Generated by Django 2.2.7 on 2019-11-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191123_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_history',
            name='deposit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Deposit'),
            preserve_default=False,
        ),
    ]
